learning_templates/first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from first_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^first-app/', include('first_app.urls')),
]

learning_templates/first_app/models.py
from django.db import models

# Create your models here.

learning_templates/first_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    my_dictionary = {'text': 'hello world', 'integer': 100}
    return render(request, 'first_app/index.html', context=my_dictionary)


def other(request):
    return render(request, 'first_app/other.html')


def relative(request):
    return render(request, 'first_app/relative-url-templates.html')

learning_templates/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django Level Four Code Examples</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li>
                    <a class="navbar-brand" href="{% url 'index' %}">Index</a>
                </li>
                <li class="navbar-link">
                    <a href="{% url 'first_app:other' %}">Other</a>
                </li>
                <li class="navbar-link">
                    <a href="{% url 'first_app:relative' %}">Relative</a>
                </li>
                <li class="navbar-link">
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body %} {% endblock %}
    </div>
</body>

</html>

learning_templates/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}

{% block body %}

{% load custom_templatetags%}

<h1>Welcome to Index Page</h1>
<h3>{{text|upper}}</h3>
<h3>{{integer|add:"99"}}</h3>
<h3>{{text|custom_cut:'world'}}</h3>

{% endblock %}

learning_templates/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body %}
    <h1>Welcome to Other Page</h1>
    <h2>This is an example of template inheritance</h2>
{% endblock body %}

learning_templates/templates/first_app/relative-url-templates.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body %}
<h1>Welcome to the Relative URL Templates Page</h1>
{% endblock body %}